// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package recordsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appointmentBelongsToPatient = `-- name: AppointmentBelongsToPatient :one
SELECT EXISTS (
  SELECT 1
  FROM appointments a
  JOIN patients p ON p.id = a.patient_id
  WHERE a.id = $1
    AND a.patient_id = $2
    AND p.psychologist_id = $3
    AND p.deleted_at IS NULL
) AS exists
`

type AppointmentBelongsToPatientParams struct {
	ID             pgtype.UUID `json:"id"`
	PatientID      pgtype.UUID `json:"patient_id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) AppointmentBelongsToPatient(ctx context.Context, arg AppointmentBelongsToPatientParams) (bool, error) {
	row := q.db.QueryRow(ctx, appointmentBelongsToPatient, arg.ID, arg.PatientID, arg.PsychologistID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
  id, start_time, end_time, reason, status, patient_id, cancelled_by_user_id,
  rescheduled_from_appointment_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
RETURNING id, start_time, end_time, reason, status, patient_id, cancelled_by_user_id, rescheduled_from_appointment_id, created_at, updated_at
`

type CreateAppointmentParams struct {
	ID                           pgtype.UUID        `json:"id"`
	StartTime                    pgtype.Timestamptz `json:"start_time"`
	EndTime                      pgtype.Timestamptz `json:"end_time"`
	Reason                       string             `json:"reason"`
	Status                       string             `json:"status"`
	PatientID                    pgtype.UUID        `json:"patient_id"`
	CancelledByUserID            pgtype.UUID        `json:"cancelled_by_user_id"`
	RescheduledFromAppointmentID pgtype.UUID        `json:"rescheduled_from_appointment_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ID,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
		arg.Status,
		arg.PatientID,
		arg.CancelledByUserID,
		arg.RescheduledFromAppointmentID,
		arg.CreatedAt,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Status,
		&i.PatientID,
		&i.CancelledByUserID,
		&i.RescheduledFromAppointmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT a.id, a.start_time, a.end_time, a.reason, a.status, a.patient_id, a.cancelled_by_user_id, a.rescheduled_from_appointment_id, a.created_at, a.updated_at
FROM appointments a
JOIN patients p ON p.id = a.patient_id
WHERE a.id = $1
  AND p.psychologist_id = $2
  AND p.deleted_at IS NULL
`

type GetAppointmentByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) GetAppointmentByID(ctx context.Context, arg GetAppointmentByIDParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, arg.ID, arg.PsychologistID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Status,
		&i.PatientID,
		&i.CancelledByUserID,
		&i.RescheduledFromAppointmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT a.id, a.start_time, a.end_time, a.reason, a.status, a.patient_id, a.cancelled_by_user_id, a.rescheduled_from_appointment_id, a.created_at, a.updated_at
FROM appointments a
JOIN patients p ON p.id = a.patient_id
WHERE p.psychologist_id = $1
  AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR a.patient_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR a.start_time >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR a.start_time <= $4::timestamptz)
  AND (
    cardinality($5::text[]) = 0
    OR a.status = ANY($5::text[])
  )
  AND (
    $6::uuid IS NULL
    OR a.id < $6::uuid
  )
  AND (
    $7::uuid IS NULL
    OR a.id > $7::uuid
  )
ORDER BY
  CASE WHEN $8::bool THEN a.id END ASC,
  CASE WHEN NOT $8::bool THEN a.id END DESC
LIMIT $9::int
`

type ListAppointmentsParams struct {
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
	PatientID      pgtype.UUID        `json:"patient_id"`
	StartDate      pgtype.Timestamptz `json:"start_date"`
	EndDate        pgtype.Timestamptz `json:"end_date"`
	Statuses       []string           `json:"statuses"`
	AfterID        pgtype.UUID        `json:"after_id"`
	BeforeID       pgtype.UUID        `json:"before_id"`
	IsBackward     bool               `json:"is_backward"`
	LimitCount     int32              `json:"limit_count"`
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.PsychologistID,
		arg.PatientID,
		arg.StartDate,
		arg.EndDate,
		arg.Statuses,
		arg.AfterID,
		arg.BeforeID,
		arg.IsBackward,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.Status,
			&i.PatientID,
			&i.CancelledByUserID,
			&i.RescheduledFromAppointmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments a
SET
  status = $3,
  cancelled_by_user_id = $4,
  updated_at = $5
FROM patients p
WHERE p.id = a.patient_id
  AND a.id = $1
  AND p.psychologist_id = $2
  AND p.deleted_at IS NULL
RETURNING a.id, a.start_time, a.end_time, a.reason, a.status, a.patient_id, a.cancelled_by_user_id, a.rescheduled_from_appointment_id, a.created_at, a.updated_at
`

type UpdateAppointmentStatusParams struct {
	ID                pgtype.UUID        `json:"id"`
	PsychologistID    pgtype.UUID        `json:"psychologist_id"`
	Status            string             `json:"status"`
	CancelledByUserID pgtype.UUID        `json:"cancelled_by_user_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus,
		arg.ID,
		arg.PsychologistID,
		arg.Status,
		arg.CancelledByUserID,
		arg.UpdatedAt,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.Status,
		&i.PatientID,
		&i.CancelledByUserID,
		&i.RescheduledFromAppointmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
