// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package recordsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (
  id, file_id, mime_type, patient_id, note_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $6
)
RETURNING id, file_id, mime_type, patient_id, note_id, created_at, updated_at, deleted_at
`

type CreateAttachmentParams struct {
	ID        pgtype.UUID        `json:"id"`
	FileID    pgtype.UUID        `json:"file_id"`
	MimeType  string             `json:"mime_type"`
	PatientID pgtype.UUID        `json:"patient_id"`
	NoteID    pgtype.UUID        `json:"note_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.FileID,
		arg.MimeType,
		arg.PatientID,
		arg.NoteID,
		arg.CreatedAt,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.MimeType,
		&i.PatientID,
		&i.NoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
UPDATE attachments att
SET deleted_at = $3, updated_at = $3
FROM patients p
WHERE p.id = att.patient_id
  AND att.id = $1
  AND p.psychologist_id = $2
  AND att.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type DeleteAttachmentParams struct {
	ID             pgtype.UUID        `json:"id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, arg.ID, arg.PsychologistID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT att.id, att.file_id, att.mime_type, att.patient_id, att.note_id, att.created_at, att.updated_at, att.deleted_at
FROM attachments att
JOIN patients p ON p.id = att.patient_id
WHERE att.id = $1
  AND p.psychologist_id = $2
  AND att.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type GetAttachmentByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, arg.ID, arg.PsychologistID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.MimeType,
		&i.PatientID,
		&i.NoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT att.id, att.file_id, att.mime_type, att.patient_id, att.note_id, att.created_at, att.updated_at, att.deleted_at
FROM attachments att
JOIN patients p ON p.id = att.patient_id
WHERE p.psychologist_id = $1
  AND att.patient_id = $2
  AND ($3::uuid IS NULL OR att.note_id = $3::uuid)
  AND att.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND (
    $4::uuid IS NULL
    OR att.id < $4::uuid
  )
  AND (
    $5::uuid IS NULL
    OR att.id > $5::uuid
  )
ORDER BY
  CASE WHEN $6::bool THEN att.id END ASC,
  CASE WHEN NOT $6::bool THEN att.id END DESC
LIMIT $7::int
`

type ListAttachmentsParams struct {
	PsychologistID pgtype.UUID `json:"psychologist_id"`
	PatientID      pgtype.UUID `json:"patient_id"`
	NoteID         pgtype.UUID `json:"note_id"`
	AfterID        pgtype.UUID `json:"after_id"`
	BeforeID       pgtype.UUID `json:"before_id"`
	IsBackward     bool        `json:"is_backward"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachments,
		arg.PsychologistID,
		arg.PatientID,
		arg.NoteID,
		arg.AfterID,
		arg.BeforeID,
		arg.IsBackward,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.MimeType,
			&i.PatientID,
			&i.NoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
