// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: familiograms.sql

package recordsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFamiliogram = `-- name: CreateFamiliogram :exec
INSERT INTO familiograms (
  id, data, patient_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $4
)
`

type CreateFamiliogramParams struct {
	ID        pgtype.UUID        `json:"id"`
	Data      []byte             `json:"data"`
	PatientID pgtype.UUID        `json:"patient_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateFamiliogram(ctx context.Context, arg CreateFamiliogramParams) error {
	_, err := q.db.Exec(ctx, createFamiliogram,
		arg.ID,
		arg.Data,
		arg.PatientID,
		arg.CreatedAt,
	)
	return err
}

const getFamiliogramByPatientID = `-- name: GetFamiliogramByPatientID :one
SELECT f.id, f.data, f.patient_id, f.created_at, f.updated_at
FROM familiograms f
JOIN patients p ON p.id = f.patient_id
WHERE f.patient_id = $1
  AND p.psychologist_id = $2
  AND p.deleted_at IS NULL
`

type GetFamiliogramByPatientIDParams struct {
	PatientID      pgtype.UUID `json:"patient_id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) GetFamiliogramByPatientID(ctx context.Context, arg GetFamiliogramByPatientIDParams) (Familiogram, error) {
	row := q.db.QueryRow(ctx, getFamiliogramByPatientID, arg.PatientID, arg.PsychologistID)
	var i Familiogram
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.PatientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFamiliogram = `-- name: UpdateFamiliogram :one
UPDATE familiograms f
SET data = $3, updated_at = $4
FROM patients p
WHERE p.id = f.patient_id
  AND f.id = $1
  AND p.psychologist_id = $2
  AND p.deleted_at IS NULL
RETURNING f.id, f.data, f.patient_id, f.created_at, f.updated_at
`

type UpdateFamiliogramParams struct {
	ID             pgtype.UUID        `json:"id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
	Data           []byte             `json:"data"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateFamiliogram(ctx context.Context, arg UpdateFamiliogramParams) (Familiogram, error) {
	row := q.db.QueryRow(ctx, updateFamiliogram,
		arg.ID,
		arg.PsychologistID,
		arg.Data,
		arg.UpdatedAt,
	)
	var i Familiogram
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.PatientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
