// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package recordsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           pgtype.UUID        `json:"id"`
	Country      string             `json:"country"`
	Province     string             `json:"province"`
	City         string             `json:"city"`
	PostalCode   string             `json:"postal_code"`
	Neighborhood string             `json:"neighborhood"`
	Street       string             `json:"street"`
	StreetNumber string             `json:"street_number"`
	UnitNumber   pgtype.Text        `json:"unit_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Appointment struct {
	ID                           pgtype.UUID        `json:"id"`
	StartTime                    pgtype.Timestamptz `json:"start_time"`
	EndTime                      pgtype.Timestamptz `json:"end_time"`
	Reason                       string             `json:"reason"`
	Status                       string             `json:"status"`
	PatientID                    pgtype.UUID        `json:"patient_id"`
	CancelledByUserID            pgtype.UUID        `json:"cancelled_by_user_id"`
	RescheduledFromAppointmentID pgtype.UUID        `json:"rescheduled_from_appointment_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type Attachment struct {
	ID           pgtype.UUID        `json:"id"`
	FileID       pgtype.UUID        `json:"file_id"`
	MimeType     string             `json:"mime_type"`
	PatientID    pgtype.UUID        `json:"patient_id"`
	NoteID       pgtype.UUID        `json:"note_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UploadStatus string             `json:"upload_status"`
}

type Familiogram struct {
	ID        pgtype.UUID        `json:"id"`
	Data      []byte             `json:"data"`
	PatientID pgtype.UUID        `json:"patient_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID            pgtype.UUID        `json:"id"`
	PatientID     pgtype.UUID        `json:"patient_id"`
	AppointmentID pgtype.UUID        `json:"appointment_id"`
	Title         pgtype.Text        `json:"title"`
	ContentHtml   string             `json:"content_html"`
	ContentText   string             `json:"content_text"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Patient struct {
	ID             pgtype.UUID        `json:"id"`
	FirstName      string             `json:"first_name"`
	MiddleName     pgtype.Text        `json:"middle_name"`
	FirstLastName  string             `json:"first_last_name"`
	SecondLastName pgtype.Text        `json:"second_last_name"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	BirthCountry   string             `json:"birth_country"`
	BirthState     string             `json:"birth_state"`
	BirthCity      string             `json:"birth_city"`
	Sex            string             `json:"sex"`
	MaritalStatus  string             `json:"marital_status"`
	Occupation     pgtype.Text        `json:"occupation"`
	Religion       pgtype.Text        `json:"religion"`
	Phone          string             `json:"phone"`
	Email          string             `json:"email"`
	AddressID      pgtype.UUID        `json:"address_id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
