// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package recordsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  id, patient_id, appointment_id, title, content_html, content_text, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $7
)
RETURNING id, patient_id, appointment_id, title, content_html, content_text, created_at, updated_at, deleted_at
`

type CreateNoteParams struct {
	ID            pgtype.UUID        `json:"id"`
	PatientID     pgtype.UUID        `json:"patient_id"`
	AppointmentID pgtype.UUID        `json:"appointment_id"`
	Title         pgtype.Text        `json:"title"`
	ContentHtml   string             `json:"content_html"`
	ContentText   string             `json:"content_text"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ID,
		arg.PatientID,
		arg.AppointmentID,
		arg.Title,
		arg.ContentHtml,
		arg.ContentText,
		arg.CreatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.AppointmentID,
		&i.Title,
		&i.ContentHtml,
		&i.ContentText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
UPDATE notes n
SET deleted_at = $3, updated_at = $3
FROM patients p
WHERE p.id = n.patient_id
  AND n.id = $1
  AND p.psychologist_id = $2
  AND n.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type DeleteNoteParams struct {
	ID             pgtype.UUID        `json:"id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.PsychologistID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT n.id, n.patient_id, n.appointment_id, n.title, n.content_html, n.content_text, n.created_at, n.updated_at, n.deleted_at
FROM notes n
JOIN patients p ON p.id = n.patient_id
WHERE n.id = $1
  AND p.psychologist_id = $2
  AND n.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type GetNoteByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.PsychologistID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.AppointmentID,
		&i.Title,
		&i.ContentHtml,
		&i.ContentText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT
  n.id,
  n.patient_id,
  n.appointment_id,
  n.title,
  n.created_at,
  n.updated_at,
  n.deleted_at
FROM notes n
JOIN patients p ON p.id = n.patient_id
WHERE p.psychologist_id = $1
  AND n.patient_id = $2
  AND n.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND ($3::timestamptz IS NULL OR n.created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR n.created_at <= $4::timestamptz)
  AND (
    NOT $5::bool
    OR n.appointment_id IS NOT NULL
  )
  AND (
    NOT $6::bool
    OR EXISTS (
      SELECT 1
      FROM attachments att
      WHERE att.note_id = n.id
        AND att.deleted_at IS NULL
    )
  )
  AND (
    $7::text = ''
    OR COALESCE(n.title, '') ILIKE '%' || $7::text || '%'
    OR n.content_text ILIKE '%' || $7::text || '%'
  )
  AND (
    $8::uuid IS NULL
    OR n.id < $8::uuid
  )
  AND (
    $9::uuid IS NULL
    OR n.id > $9::uuid
  )
ORDER BY
  CASE WHEN $10::bool THEN n.id END ASC,
  CASE WHEN NOT $10::bool THEN n.id END DESC
LIMIT $11::int
`

type ListNotesParams struct {
	PsychologistID            pgtype.UUID        `json:"psychologist_id"`
	PatientID                 pgtype.UUID        `json:"patient_id"`
	StartDate                 pgtype.Timestamptz `json:"start_date"`
	EndDate                   pgtype.Timestamptz `json:"end_date"`
	WithAppointmentAssociated bool               `json:"with_appointment_associated"`
	WithFilesAssociated       bool               `json:"with_files_associated"`
	SearchQuery               string             `json:"search_query"`
	AfterID                   pgtype.UUID        `json:"after_id"`
	BeforeID                  pgtype.UUID        `json:"before_id"`
	IsBackward                bool               `json:"is_backward"`
	LimitCount                int32              `json:"limit_count"`
}

type ListNotesRow struct {
	ID            pgtype.UUID        `json:"id"`
	PatientID     pgtype.UUID        `json:"patient_id"`
	AppointmentID pgtype.UUID        `json:"appointment_id"`
	Title         pgtype.Text        `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.PsychologistID,
		arg.PatientID,
		arg.StartDate,
		arg.EndDate,
		arg.WithAppointmentAssociated,
		arg.WithFilesAssociated,
		arg.SearchQuery,
		arg.AfterID,
		arg.BeforeID,
		arg.IsBackward,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesRow{}
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.AppointmentID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteBelongsToPatient = `-- name: NoteBelongsToPatient :one
SELECT EXISTS (
  SELECT 1
  FROM notes n
  JOIN patients p ON p.id = n.patient_id
  WHERE n.id = $1
    AND n.patient_id = $2
    AND p.psychologist_id = $3
    AND n.deleted_at IS NULL
    AND p.deleted_at IS NULL
) AS exists
`

type NoteBelongsToPatientParams struct {
	ID             pgtype.UUID `json:"id"`
	PatientID      pgtype.UUID `json:"patient_id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) NoteBelongsToPatient(ctx context.Context, arg NoteBelongsToPatientParams) (bool, error) {
	row := q.db.QueryRow(ctx, noteBelongsToPatient, arg.ID, arg.PatientID, arg.PsychologistID)
	var exists bool
err := row.Scan(&exists)
return exists, err
}

const noteExists = `-- name: NoteExists :one
SELECT EXISTS (
  SELECT 1
  FROM notes n
  JOIN patients p ON p.id = n.patient_id
  WHERE n.id = $1
    AND p.psychologist_id = $2
    AND n.deleted_at IS NULL
    AND p.deleted_at IS NULL
) AS exists
`

type NoteExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) NoteExists(ctx context.Context, arg NoteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, noteExists, arg.ID, arg.PsychologistID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateNote = `-- name: UpdateNote :execrows
UPDATE notes n
SET
  appointment_id = COALESCE($1, n.appointment_id),
  title = COALESCE($2, n.title),
  content_html = COALESCE($3, n.content_html),
  content_text = COALESCE($4, n.content_text),
  updated_at = $5
FROM patients p
WHERE p.id = n.patient_id
  AND n.id = $6
  AND p.psychologist_id = $7
  AND n.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type UpdateNoteParams struct {
	AppointmentID  pgtype.UUID        `json:"appointment_id"`
	Title          pgtype.Text        `json:"title"`
	ContentHtml    pgtype.Text        `json:"content_html"`
	ContentText    pgtype.Text        `json:"content_text"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNote,
		arg.AppointmentID,
		arg.Title,
		arg.ContentHtml,
		arg.ContentText,
		arg.UpdatedAt,
		arg.ID,
		arg.PsychologistID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
