// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package recordsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :exec
INSERT INTO addresses (
  id, country, province, city, postal_code, neighborhood, street, street_number,
  unit_number, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10
)
`

type CreateAddressParams struct {
	ID           pgtype.UUID        `json:"id"`
	Country      string             `json:"country"`
	Province     string             `json:"province"`
	City         string             `json:"city"`
	PostalCode   string             `json:"postal_code"`
	Neighborhood string             `json:"neighborhood"`
	Street       string             `json:"street"`
	StreetNumber string             `json:"street_number"`
	UnitNumber   pgtype.Text        `json:"unit_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.Exec(ctx, createAddress,
		arg.ID,
		arg.Country,
		arg.Province,
		arg.City,
		arg.PostalCode,
		arg.Neighborhood,
		arg.Street,
		arg.StreetNumber,
		arg.UnitNumber,
		arg.CreatedAt,
	)
	return err
}

const createPatient = `-- name: CreatePatient :exec
INSERT INTO patients (
  id, first_name, middle_name, first_last_name, second_last_name, birth_date,
  birth_country, birth_state, birth_city, sex, marital_status, occupation,
  religion, phone, email, address_id, psychologist_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $18
)
`

type CreatePatientParams struct {
	ID             pgtype.UUID        `json:"id"`
	FirstName      string             `json:"first_name"`
	MiddleName     pgtype.Text        `json:"middle_name"`
	FirstLastName  string             `json:"first_last_name"`
	SecondLastName pgtype.Text        `json:"second_last_name"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	BirthCountry   string             `json:"birth_country"`
	BirthState     string             `json:"birth_state"`
	BirthCity      string             `json:"birth_city"`
	Sex            string             `json:"sex"`
	MaritalStatus  string             `json:"marital_status"`
	Occupation     pgtype.Text        `json:"occupation"`
	Religion       pgtype.Text        `json:"religion"`
	Phone          string             `json:"phone"`
	Email          string             `json:"email"`
	AddressID      pgtype.UUID        `json:"address_id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) error {
	_, err := q.db.Exec(ctx, createPatient,
		arg.ID,
		arg.FirstName,
		arg.MiddleName,
		arg.FirstLastName,
		arg.SecondLastName,
		arg.BirthDate,
		arg.BirthCountry,
		arg.BirthState,
		arg.BirthCity,
		arg.Sex,
		arg.MaritalStatus,
		arg.Occupation,
		arg.Religion,
		arg.Phone,
		arg.Email,
		arg.AddressID,
		arg.PsychologistID,
		arg.CreatedAt,
	)
	return err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT
  p.id,
  p.first_name,
  p.middle_name,
  p.first_last_name,
  p.second_last_name,
  p.birth_date,
  p.birth_country,
  p.birth_state,
  p.birth_city,
  p.sex,
  p.marital_status,
  p.occupation,
  p.religion,
  p.phone,
  p.email,
  p.psychologist_id,
  p.created_at,
  p.updated_at,
  p.deleted_at,
  a.id AS address_id,
  a.country AS address_country,
  a.province AS address_province,
  a.city AS address_city,
  a.postal_code AS address_postal_code,
  a.neighborhood AS address_neighborhood,
  a.street AS address_street,
  a.street_number AS address_street_number,
  a.unit_number AS address_unit_number,
  a.created_at AS address_created_at,
  a.updated_at AS address_updated_at,
  a.deleted_at AS address_deleted_at
FROM patients p
JOIN addresses a ON a.id = p.address_id
WHERE p.id = $1
  AND p.psychologist_id = $2
  AND p.deleted_at IS NULL
`

type GetPatientByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

type GetPatientByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FirstName           string             `json:"first_name"`
	MiddleName          pgtype.Text        `json:"middle_name"`
	FirstLastName       string             `json:"first_last_name"`
	SecondLastName      pgtype.Text        `json:"second_last_name"`
	BirthDate           pgtype.Date        `json:"birth_date"`
	BirthCountry        string             `json:"birth_country"`
	BirthState          string             `json:"birth_state"`
	BirthCity           string             `json:"birth_city"`
	Sex                 string             `json:"sex"`
	MaritalStatus       string             `json:"marital_status"`
	Occupation          pgtype.Text        `json:"occupation"`
	Religion            pgtype.Text        `json:"religion"`
	Phone               string             `json:"phone"`
	Email               string             `json:"email"`
	PsychologistID      pgtype.UUID        `json:"psychologist_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	AddressID           pgtype.UUID        `json:"address_id"`
	AddressCountry      string             `json:"address_country"`
	AddressProvince     string             `json:"address_province"`
	AddressCity         string             `json:"address_city"`
	AddressPostalCode   string             `json:"address_postal_code"`
	AddressNeighborhood string             `json:"address_neighborhood"`
	AddressStreet       string             `json:"address_street"`
	AddressStreetNumber string             `json:"address_street_number"`
	AddressUnitNumber   pgtype.Text        `json:"address_unit_number"`
	AddressCreatedAt    pgtype.Timestamptz `json:"address_created_at"`
	AddressUpdatedAt    pgtype.Timestamptz `json:"address_updated_at"`
	AddressDeletedAt    pgtype.Timestamptz `json:"address_deleted_at"`
}

func (q *Queries) GetPatientByID(ctx context.Context, arg GetPatientByIDParams) (GetPatientByIDRow, error) {
	row := q.db.QueryRow(ctx, getPatientByID, arg.ID, arg.PsychologistID)
	var i GetPatientByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.FirstLastName,
		&i.SecondLastName,
		&i.BirthDate,
		&i.BirthCountry,
		&i.BirthState,
		&i.BirthCity,
		&i.Sex,
		&i.MaritalStatus,
		&i.Occupation,
		&i.Religion,
		&i.Phone,
		&i.Email,
		&i.PsychologistID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AddressID,
		&i.AddressCountry,
		&i.AddressProvince,
		&i.AddressCity,
		&i.AddressPostalCode,
		&i.AddressNeighborhood,
		&i.AddressStreet,
		&i.AddressStreetNumber,
		&i.AddressUnitNumber,
		&i.AddressCreatedAt,
		&i.AddressUpdatedAt,
		&i.AddressDeletedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT
  p.id,
  p.first_name,
  p.middle_name,
  p.first_last_name,
  p.second_last_name,
  p.birth_date,
  p.email,
  p.phone
FROM patients p
WHERE p.psychologist_id = $1
  AND p.deleted_at IS NULL
  AND (
    $2::text = ''
    OR p.first_name ILIKE '%' || $2::text || '%'
    OR COALESCE(p.middle_name, '') ILIKE '%' || $2::text || '%'
    OR p.first_last_name ILIKE '%' || $2::text || '%'
    OR COALESCE(p.second_last_name, '') ILIKE '%' || $2::text || '%'
    OR p.email ILIKE '%' || $2::text || '%'
    OR p.phone ILIKE '%' || $2::text || '%'
  )
  AND (
    NOT $3::bool
    OR EXISTS (
      SELECT 1
      FROM appointments ap
      WHERE ap.patient_id = p.id
        AND ap.status = 'APPOINTMENT_STATUS_SCHEDULED'
        AND ap.start_time >= now()
    )
  )
  AND (
    NOT $4::bool
    OR NOT EXISTS (
      SELECT 1
      FROM appointments ap
      WHERE ap.patient_id = p.id
    )
  )
  AND (
    NOT $5::bool
    OR EXISTS (
      SELECT 1
      FROM appointments ap
      WHERE ap.patient_id = p.id
    )
  )
  AND (
    $6::uuid IS NULL
    OR p.id < $6::uuid
  )
  AND (
    $7::uuid IS NULL
    OR p.id > $7::uuid
  )
ORDER BY
  CASE WHEN $8::bool THEN p.id END ASC,
  CASE WHEN NOT $8::bool THEN p.id END DESC
LIMIT $9::int
`

type ListPatientsParams struct {
	PsychologistID          pgtype.UUID `json:"psychologist_id"`
	SearchQuery             string      `json:"search_query"`
	WithPendingAppointments bool        `json:"with_pending_appointments"`
	WithNoAppointments      bool        `json:"with_no_appointments"`
	EverHadAppointments     bool        `json:"ever_had_appointments"`
	AfterID                 pgtype.UUID `json:"after_id"`
	BeforeID                pgtype.UUID `json:"before_id"`
	IsBackward              bool        `json:"is_backward"`
	LimitCount              int32       `json:"limit_count"`
}

type ListPatientsRow struct {
	ID             pgtype.UUID `json:"id"`
	FirstName      string      `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	FirstLastName  string      `json:"first_last_name"`
	SecondLastName pgtype.Text `json:"second_last_name"`
	BirthDate      pgtype.Date `json:"birth_date"`
	Email          string      `json:"email"`
	Phone          string      `json:"phone"`
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients,
		arg.PsychologistID,
		arg.SearchQuery,
		arg.WithPendingAppointments,
		arg.WithNoAppointments,
		arg.EverHadAppointments,
		arg.AfterID,
		arg.BeforeID,
		arg.IsBackward,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatientsRow{}
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.MiddleName,
			&i.FirstLastName,
			&i.SecondLastName,
			&i.BirthDate,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientExists = `-- name: PatientExists :one
SELECT EXISTS (
  SELECT 1
  FROM patients
  WHERE id = $1
    AND psychologist_id = $2
    AND deleted_at IS NULL
) AS exists
`

type PatientExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	PsychologistID pgtype.UUID `json:"psychologist_id"`
}

func (q *Queries) PatientExists(ctx context.Context, arg PatientExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, patientExists, arg.ID, arg.PsychologistID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateAddressByPatientID = `-- name: UpdateAddressByPatientID :execrows
UPDATE addresses a
SET
  country = COALESCE($1, a.country),
  province = COALESCE($2, a.province),
  city = COALESCE($3, a.city),
  postal_code = COALESCE($4, a.postal_code),
  neighborhood = COALESCE($5, a.neighborhood),
  street = COALESCE($6, a.street),
  street_number = COALESCE($7, a.street_number),
  unit_number = COALESCE($8, a.unit_number),
  updated_at = $9
FROM patients p
WHERE p.address_id = a.id
  AND p.id = $10
  AND p.psychologist_id = $11
  AND p.deleted_at IS NULL
`

type UpdateAddressByPatientIDParams struct {
	Country        pgtype.Text        `json:"country"`
	Province       pgtype.Text        `json:"province"`
	City           pgtype.Text        `json:"city"`
	PostalCode     pgtype.Text        `json:"postal_code"`
	Neighborhood   pgtype.Text        `json:"neighborhood"`
	Street         pgtype.Text        `json:"street"`
	StreetNumber   pgtype.Text        `json:"street_number"`
	UnitNumber     pgtype.Text        `json:"unit_number"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PatientID      pgtype.UUID        `json:"patient_id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
}

func (q *Queries) UpdateAddressByPatientID(ctx context.Context, arg UpdateAddressByPatientIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAddressByPatientID,
		arg.Country,
		arg.Province,
		arg.City,
		arg.PostalCode,
		arg.Neighborhood,
		arg.Street,
		arg.StreetNumber,
		arg.UnitNumber,
		arg.UpdatedAt,
		arg.PatientID,
		arg.PsychologistID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePatientContact = `-- name: UpdatePatientContact :execrows
UPDATE patients
SET
  phone = COALESCE($1, phone),
  email = COALESCE($2, email),
  updated_at = $3
WHERE id = $4
  AND psychologist_id = $5
  AND deleted_at IS NULL
`

type UpdatePatientContactParams struct {
	Phone          pgtype.Text        `json:"phone"`
	Email          pgtype.Text        `json:"email"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
}

func (q *Queries) UpdatePatientContact(ctx context.Context, arg UpdatePatientContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePatientContact,
		arg.Phone,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
		arg.PsychologistID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePatientIdentification = `-- name: UpdatePatientIdentification :execrows
UPDATE patients
SET
  first_name = COALESCE($1, first_name),
  middle_name = COALESCE($2, middle_name),
  first_last_name = COALESCE($3, first_last_name),
  second_last_name = COALESCE($4, second_last_name),
  birth_date = COALESCE($5, birth_date),
  sex = COALESCE($6, sex),
  birth_country = COALESCE($7, birth_country),
  birth_state = COALESCE($8, birth_state),
  birth_city = COALESCE($9, birth_city),
  occupation = COALESCE($10, occupation),
  marital_status = COALESCE($11, marital_status),
  religion = COALESCE($12, religion),
  updated_at = $13
WHERE id = $14
  AND psychologist_id = $15
  AND deleted_at IS NULL
`

type UpdatePatientIdentificationParams struct {
	FirstName      pgtype.Text        `json:"first_name"`
	MiddleName     pgtype.Text        `json:"middle_name"`
	FirstLastName  pgtype.Text        `json:"first_last_name"`
	SecondLastName pgtype.Text        `json:"second_last_name"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	Sex            pgtype.Text        `json:"sex"`
	BirthCountry   pgtype.Text        `json:"birth_country"`
	BirthState     pgtype.Text        `json:"birth_state"`
	BirthCity      pgtype.Text        `json:"birth_city"`
	Occupation     pgtype.Text        `json:"occupation"`
	MaritalStatus  pgtype.Text        `json:"marital_status"`
	Religion       pgtype.Text        `json:"religion"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
	PsychologistID pgtype.UUID        `json:"psychologist_id"`
}

func (q *Queries) UpdatePatientIdentification(ctx context.Context, arg UpdatePatientIdentificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePatientIdentification,
		arg.FirstName,
		arg.MiddleName,
		arg.FirstLastName,
		arg.SecondLastName,
		arg.BirthDate,
		arg.Sex,
		arg.BirthCountry,
		arg.BirthState,
		arg.BirthCity,
		arg.Occupation,
		arg.MaritalStatus,
		arg.Religion,
		arg.UpdatedAt,
		arg.ID,
		arg.PsychologistID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
