name: neuraclinic-records

services:
  neuraclinic-records:
    container_name: neuraclinic-records
    restart: unless-stopped
    env_file: ../.env
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8003:8000
    volumes:
      - ../:/app-src
      - ../certs:/app/certs:ro
      - ../../neuraclinic-file-management/certs:/app/file-management-certs:ro
    environment:
      ENVIRONMENT: development
      AUTO_RUN_MIGRATIONS: "true"
    depends_on:
      neuraclinic-records-db:
        condition: service_healthy
    networks:
      - neuraclinic-network
      - neuraclinic-records-network

  neuraclinic-records-db:
    image: postgres:17.6
    container_name: neuraclinic-records-db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: neuraclinic-records
      TZ: America/Hermosillo
    volumes:
      - neuraclinic-records-db-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - neuraclinic-records-network

  neuraclinic-records-adminer:
    image: adminer
    container_name: neuraclinic-records-adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8086:8080
    depends_on:
      neuraclinic-records-db:
        condition: service_started
    networks:
      - neuraclinic-records-network

networks:
  neuraclinic-network:
    external: true
  neuraclinic-records-network:
    driver: bridge

volumes:
  neuraclinic-records-db-data:
    name: neuraclinic-records-db-data

